### PR TITLE
Fix count query when using params.knex

### LINKED ISSUE #121: Wrong total if params.knex is set
If params.knex is set, params.query is bypassed, and the knex query is executed insted. However, for the count query (ie total), the params.query is taken into account (instead of params.knex), and results in a wrong total.

I think this is inconsistant, shouldn't params.knex, if set, should be used to compute the count query?

### PR DESCRIPTION
**Pull request by omeid**
Fixes #121

### CODE REVIEW

**Comment by daffl** [comment]
Great, thank you!

**Comment by omeid** [comment]
Should not that until griesser/knex#51 is addressed, this will break when using with `.distinct()` :(

**Comment by omeid** [comment]
A workaround is to use a sub-query when doing distinct, so  `SELECT * FROM (SELECT .....)` and then the count would work fine.

**Comment by cjbland** [comment]
I don't mean to revive an old PR, but I was hoping @omeid could give a little more details on your workaround? If the table's `id` column does not exist as part of the distinct clause, the count will not work. This is the issue I'm running into right now because of this line: https://github.com/feathersjs-ecosystem/feathers-knex/blob/e7f04f34d45be5c00ca7848fac1c51c9ac36703c/lib/index.js#L193

**Pull request merged**
