### PR TITLE
add ilike operator

### PR DESCRIPTION
**Pull request by sylvainlap**
Allows to support the postgres ILIKE operator.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! Is there any other operators you think we should map? New operators also need to be added to the documentation at https://docs.feathersjs.com/api/databases/knexjs.html#querying.

**Comment by sylvainlap** [comment]
the documentation has been updated here: https://github.com/feathersjs/docs/pull/886

**Comment by daffl** [comment]
Sweet, thank you. A test would be nice as well. Probably just a copy of https://github.com/feathersjs-ecosystem/feathers-knex/blob/master/test/index.test.js#L106 querying for `%char%`

**Comment by sylvainlap** [comment]
I cannot add a test, because your tests run sqlite, and ilike is a psql only operator.

**Comment by daffl** [comment]
Makes sense. I created a follow-up issue in #128 to run CI against other dbs as well so we can revisit this then.

**Pull request merged**
