### PR TITLE
Catch unhandled transaction rejections

### PR DESCRIPTION
**Pull request by vonagam**
`transaction()` returns a transaction promise. When `rollback()` is called that promise is rejected.

Currently this rejection is not handled and causes many errors about `Unhandled rejection...` while running tests.

This rejection is to force people to log and handle underlying errors, so that they are not simply silenced by `.catch(trx.rollback)`. But in feathers one expected to setup logger on app level for errors. Because of this we can simple silence this promise rejection.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request! I'm not sure I understand why the error should be swallowed here though. Wouldn't you still want to get an error if the rollback goes wrong?

**Comment by vonagam** [comment]
You can read details for example in this [issue discussion](https://github.com/tgriesser/knex/issues/2083) or you can try to understand [source code](https://github.com/tgriesser/knex/blob/master/src/transaction.js).

Basically this error which is being shallowed there is the exact one which you pass to `.rollback` (`context.error`). It is kinda doable firing: you catch an error in your code, execute rollback, rollback throws transaction's promise with passed error, you expected to catch error and log it. (Second example in [documentation for transactions](https://knexjs.org/#Transactions))

It is kinda confusing to explain... But you have fully working tests and they are logging those errors which you actually handle (for example [travis log from last pull](https://travis-ci.org/feathersjs-ecosystem/feathers-knex/jobs/398351544))

**Comment by vonagam** [comment]
[Rollback](https://github.com/tgriesser/knex/blob/cb3a85e73813f485f6fa120de72df137cc20606c/src/transaction.js#L100) returns promise for its query, so any errors of rollback itself will be handled [there](https://github.com/feathersjs/feathers/blob/6b05a118792e4bb92d1a76f76a9962017e915144/lib/hooks.js#L108) in feathers errors hooks runner as you [return](https://github.com/feathersjs-ecosystem/feathers-knex/blob/f828d2647b7316664f6b793aafd866e31974d8b5/lib/hooks.js#L51) that promise from hook.

(The only instance where it seems like it might be a problem is `Promise.TimeoutError`, which they catch specifically [there](https://github.com/tgriesser/knex/blob/cb3a85e73813f485f6fa120de72df137cc20606c/src/transaction.js#L103))

**Comment by vonagam** [comment]
Hm... seems like i am mistaken though...

Yeah, you are right about errors in rollback itself. All errors are beign shallowed [there](https://github.com/tgriesser/knex/blob/cb3a85e73813f485f6fa120de72df137cc20606c/src/transaction.js#L118). So promise might be rejected either with passed error to `rollback` or it might be error from commit/rollback query itself...

**Comment by vonagam** [comment]
One way to distinguish one from another is to wrap `hook.error` in something (new error subclass) before passing to `rollback`. And in transaction's promise to check if it is wrapped or not. If it is wrapped we can ignore it, if it is not then we need at least to throw it up.

**Comment by vonagam** [comment]
Ok, updated code.

Now we skip errors which we are already handled and throw up errors which are new.

Only downside is `Promise.TimeoutError` of rollback query, because it [rejects](https://github.com/tgriesser/knex/blob/cb3a85e73813f485f6fa120de72df137cc20606c/src/transaction.js#L104) transaction's promise with same error which we pass to rollback there is no way to distinguish between successful rollback and timed-out one.

**Comment by vonagam** [comment]
Added optional `catch` option for `start` hook.

**Comment by daffl** [comment]
Would it be possible to add a test? I'm still not sure I'm fully following the problem. A test case might make it more clear and having tests is always a good thing anyway 😄

**Comment by vonagam** [comment]
I though about how to explain. Maybe this will help.
This is how you create a usual promise:

```js
var promise = new Promise(function(resolve, reject) {
  ...
});
```

And this is how you create a knex transaction promise:

```js
var transactionPromise = knex.transaction(({commit, rollback}) => {
  ...
});
```

`commit` and `rollback` act like `resolve` and `reject`, but additionaly they commit or rollback queries.

There are three reasons, why transaction promise might be rejected:
1) You called `rollback`, and it successed.
2) You called `rollback`, but it failed.
3) You called `commit`, but it failed.

What i want to do is to silence first type of errors, because we already handle them inside feathers flow (we call `rollback` as part of that handling flow). But we don't want to silence second and third type of errors, and we actually want to fail on those (turns out currently we don't fail on third type of errors).

So what i did, is wrapped error before passing it to `rollback` (ala `reject`), and in `transactionPromise.catch` i check if it is wrapped or not to determine its kind.

In test logs before this pull you see warnings about unhandled rejections, in logs of this pull there are none. From that you can see that silencing part is working, what remains to test is failing on second and third type of errors.

To simulate those errors you need to force internals of knex to fail. It is hacky and not cool, but i managed...

Turns out, that before you have not handled commit failures. Before this pull, if you call `commit` but it fails (third type), then a service still thinks that everything is ok and returns you a result. So this pull is not only about fixing annoying warnings, but actually fixes some stuff.

Also, while figuring out tests, it seems like [those](https://github.com/feathersjs-ecosystem/feathers-knex/blob/f828d2647b7316664f6b793aafd866e31974d8b5/test/index.test.js#L156-L178) test lines does not do what you want. Because `hooks` does add hooks, not replaces them.

**Comment by vonagam** [comment]
@daffl ping.

**Comment by shadowRR** [comment]
@daffl Could you take a look at this ? Still getting unhandled rejection since this pull request hasn't been merged yet...

**Comment by daffl** [comment]
Sorry about that. Released as version 4.0.0 (due to the breaking update of the `knex` dependency).

**Pull request merged**
